# Generated by Django 6.1.1 on 2026-09-04 01:37

from django.db import migrations, models


def populate_payment_breakdown(apps, schema_editor):
    Invoice = apps.get_model('payments', 'Invoice')
    Transaction = apps.get_model('payments', 'Transaction')
    Decimal = __import__('decimal').Decimal

    for invoice in Invoice.objects.select_related('booking'):
        quote = invoice.booking.quoted_price
        reservation = (quote * Decimal('0.20')).quantize(Decimal('0.01'))
        invoice.total_amount = quote
        invoice.reservation_amount = reservation
        invoice.balance_amount = quote - reservation
        invoice.save(update_fields=('total_amount', 'reservation_amount', 'balance_amount'))
        for transaction in invoice.transactions.all():
            if transaction.amount == invoice.balance_amount:
                transaction.purpose = 'balance'
                transaction.save(update_fields=('purpose',))


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payout_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reservation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reservation_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('reservation', 'Reservation fee'), ('balance', 'Final balance')], default='reservation', max_length=20),
        ),
        migrations.RunPython(populate_payment_breakdown, migrations.RunPython.noop),
    ]
