# Generated by Django 6.1.1 on 2026-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this photographer in the featured directory.'),
        ),
    ]
