# Generated by Django 6.1.1 on 2026-09-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_galleryaccess_password_hash'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clientnote',
            constraint=models.CheckConstraint(condition=models.Q(('photographer', models.F('client')), _negated=True), name='note_distinct_users'),
        ),
    ]
