# Generated by Django 6.1.1 on 2026-09-04 01:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_service_types(apps, schema_editor):
    ServiceType = apps.get_model('bookings', 'ServiceType')
    service_types = [
        ('Studio shoot', 'studio-shoot', 'Controlled portraits, fashion, headshots, and editorial sessions.', '15000.00', 10),
        ('Outdoor shoot', 'outdoor-shoot', 'Natural-light portraits, couple sessions, and lifestyle stories.', '12000.00', 20),
        ('Reels package', 'reels-package', 'Short-form social clips with shooting and simple edit direction.', '18000.00', 30),
        ('Video production', 'video-production', 'A polished music, brand, interview, or event video.', '35000.00', 40),
        ('Wedding coverage', 'wedding-coverage', 'Full-day wedding storytelling with a tailored coverage plan.', '80000.00', 50),
        ('Burial & memorial', 'burial-memorial', 'Respectful photo and video coverage for memorial gatherings.', '25000.00', 60),
        ('Corporate & events', 'corporate-events', 'Conferences, launches, dinners, and team documentation.', '30000.00', 70),
        ('Product & brand', 'product-brand', 'Product, menu, campaign, and small-business content.', '20000.00', 80),
    ]
    for name, slug, description, price, sort_order in service_types:
        ServiceType.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'description': description,
                'suggested_price': Decimal(price),
                'sort_order': sort_order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_status',
            field=models.CharField(choices=[('due', 'Reservation fee due'), ('held', 'Held in escrow'), ('released', 'Released to photographer'), ('refunded', 'Refunded')], default='due', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='work_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reservation_due', 'Reservation fee due'), ('reserved', 'Reserved'), ('arrival_confirmed', 'Arrival confirmed'), ('balance_due', 'Balance due'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed (legacy)')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.servicetype'),
        ),
        migrations.RunPython(seed_service_types, migrations.RunPython.noop),
    ]
